from PyQt6 import QtCore, QtGui, QtWidgets

global currentMenu

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 620)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuPages = QtWidgets.QVBoxLayout()
        self.menuPages.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.menuPages.setObjectName("menuPages")
        self.mainPage = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainPage.sizePolicy().hasHeightForWidth())
        self.mainPage.setSizePolicy(sizePolicy)
        self.mainPage.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(16)
        self.mainPage.setFont(font)
        self.mainPage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.mainPage.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.mainPage.setStyleSheet("pushButton.setStyleSheet(\"text-align:left;\")")
        self.mainPage.setCheckable(True)
        self.mainPage.setObjectName("mainPage")
        self.menuPages.addWidget(self.mainPage)
        self.petsPage = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.petsPage.sizePolicy().hasHeightForWidth())
        self.petsPage.setSizePolicy(sizePolicy)
        self.petsPage.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(16)
        self.petsPage.setFont(font)
        self.petsPage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.petsPage.setCheckable(True)
        self.petsPage.setObjectName("petsPage")
        self.menuPages.addWidget(self.petsPage)
        self.schedPage = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedPage.sizePolicy().hasHeightForWidth())
        self.schedPage.setSizePolicy(sizePolicy)
        self.schedPage.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(16)
        self.schedPage.setFont(font)
        self.schedPage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.schedPage.setCheckable(True)
        self.schedPage.setObjectName("schedPage")
        self.menuPages.addWidget(self.schedPage)
        self.cagesPage = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cagesPage.sizePolicy().hasHeightForWidth())
        self.cagesPage.setSizePolicy(sizePolicy)
        self.cagesPage.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(16)
        self.cagesPage.setFont(font)
        self.cagesPage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.cagesPage.setCheckable(True)
        self.cagesPage.setObjectName("cagesPage")
        self.menuPages.addWidget(self.cagesPage)
        self.horizontalLayout_2.addLayout(self.menuPages)
        self.scrollAreaContainer = QtWidgets.QVBoxLayout()
        self.scrollAreaContainer.setContentsMargins(-1, 0, 0, -1)
        self.scrollAreaContainer.setObjectName("scrollAreaContainer")
        self.scrollAreaMenu = QtWidgets.QHBoxLayout()
        self.scrollAreaMenu.setContentsMargins(-1, 0, -1, -1)
        self.scrollAreaMenu.setObjectName("scrollAreaMenu")
        self.pushToCreateM = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(12)
        self.pushToCreateM.setFont(font)
        self.pushToCreateM.setObjectName("pushToCreateM")
        self.scrollAreaMenu.addWidget(self.pushToCreateM)
        self.pushToRedactM = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(12)
        self.pushToRedactM.setFont(font)
        self.pushToRedactM.setObjectName("pushToRedactM")
        self.scrollAreaMenu.addWidget(self.pushToRedactM)
        self.pushToSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(12)
        self.pushToSearch.setFont(font)
        self.pushToSearch.setObjectName("pushToSearch")
        self.scrollAreaMenu.addWidget(self.pushToSearch)
        self.searchWhat = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.searchWhat.setObjectName("searchWhat")
        self.scrollAreaMenu.addWidget(self.searchWhat)
        self.scrollAreaMenu.setStretch(0, 2)
        self.scrollAreaMenu.setStretch(1, 2)
        self.scrollAreaMenu.setStretch(2, 2)
        self.scrollAreaMenu.setStretch(3, 5)
        self.scrollAreaContainer.addLayout(self.scrollAreaMenu)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 671, 570))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollAreaContainer.addWidget(self.scrollArea)
        self.horizontalLayout_2.addLayout(self.scrollAreaContainer)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        #self.petsMenuGui(MainWindow)
        self.mainMenuGui(MainWindow)


        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def mainMenuGui(self, MainWindow):
        currentMenu = 0
        self.schedDay = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.schedDay.sizePolicy().hasHeightForWidth())
        self.schedDay.setSizePolicy(sizePolicy)
        self.schedDay.setMinimumSize(QtCore.QSize(250, 250))
        self.schedDay.setMaximumSize(QtCore.QSize(500, 1000))
        self.schedDay.setStyleSheet("QWidget.SchedDay.border: 2px solid black")
        self.schedDay.setObjectName("schedDay")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.schedDay)
        self.verticalLayout_2.setContentsMargins(-1, -1, 11, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.daySched_L = QtWidgets.QLabel(parent=self.schedDay)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(20)
        self.daySched_L.setFont(font)
        self.daySched_L.setStyleSheet("border: 2px solid black")
        self.daySched_L.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daySched_L.setObjectName("daySched_L")
        self.verticalLayout_2.addWidget(self.daySched_L)
        self.containerEvent = QtWidgets.QWidget(parent=self.schedDay)
        self.containerEvent.setStyleSheet("")
        self.containerEvent.setObjectName("containerEvent")
        self.formLayout = QtWidgets.QFormLayout(self.containerEvent)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.RowWrapPolicy.WrapLongRows)
        self.formLayout.setLabelAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setFormAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout.setContentsMargins(0, 5, 5, -1)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.eventName_L = QtWidgets.QLabel(parent=self.containerEvent)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(24)
        self.eventName_L.setFont(font)
        self.eventName_L.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.eventName_L.setObjectName("eventName_L")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.eventName_L)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)
        self.eventActions = QtWidgets.QHBoxLayout()
        self.eventActions.setContentsMargins(-1, 0, -1, -1)
        self.eventActions.setObjectName("eventActions")
        self.pushToDo = QtWidgets.QPushButton(parent=self.containerEvent)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(12)
        self.pushToDo.setFont(font)
        self.pushToDo.setObjectName("pushToDo")
        self.eventActions.addWidget(self.pushToDo)
        self.pushToRedact = QtWidgets.QPushButton(parent=self.containerEvent)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(12)
        self.pushToRedact.setFont(font)
        self.pushToRedact.setObjectName("pushToRedact")
        self.eventActions.addWidget(self.pushToRedact)
        self.pushToCancel = QtWidgets.QPushButton(parent=self.containerEvent)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(12)
        self.pushToCancel.setFont(font)
        self.pushToCancel.setObjectName("pushToCancel")
        self.eventActions.addWidget(self.pushToCancel)
        self.isDone_L = QtWidgets.QLabel(parent=self.containerEvent)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(12)
        self.isDone_L.setFont(font)
        self.isDone_L.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.isDone_L.setObjectName("isDone_L")
        self.eventActions.addWidget(self.isDone_L)
        self.eventActions.setStretch(0, 2)
        self.eventActions.setStretch(1, 4)
        self.eventActions.setStretch(2, 2)
        self.eventActions.setStretch(3, 4)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.eventActions)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem1)
        self.dateOfEvent_L = QtWidgets.QLabel(parent=self.containerEvent)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(12)
        self.dateOfEvent_L.setFont(font)
        self.dateOfEvent_L.setObjectName("dateOfEvent_L")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateOfEvent_L)
        self.descName_L = QtWidgets.QLabel(parent=self.containerEvent)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.descName_L.setFont(font)
        self.descName_L.setObjectName("descName_L")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.descName_L)
        self.verticalLayout_2.addWidget(self.containerEvent)
        self.horizontalLayout.addWidget(self.schedDay)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        _translate = QtCore.QCoreApplication.translate
        self.daySched_L.setText(_translate("MainWindow", "Сегодня"))
        self.eventName_L.setText(_translate("MainWindow", "Название"))
        self.pushToDo.setText(_translate("MainWindow", "Сделать"))
        self.pushToRedact.setText(_translate("MainWindow", "Редактировать"))
        self.pushToCancel.setText(_translate("MainWindow", "Отменить"))
        self.isDone_L.setText(_translate("MainWindow", "Сделано"))
        self.dateOfEvent_L.setText(_translate("MainWindow", "Ежедневное"))
        self.descName_L.setText(_translate("MainWindow", "Описание"))


    def petsMenuGui(self,MainWindow):
        self.containerPet = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.containerPet.setStyleSheet("")
        self.containerPet.setObjectName("containerPet")
        self.formLayout = QtWidgets.QFormLayout(self.containerPet)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.RowWrapPolicy.WrapLongRows)
        self.formLayout.setLabelAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setFormAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout.setContentsMargins(0, 5, 5, -1)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.petPhoto = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(15)
        self.petPhoto.setFont(font)
        self.petPhoto.setText("")
        self.petPhoto.setPixmap(QtGui.QPixmap("../maket/car.png"))
        self.petPhoto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.petPhoto.setObjectName("petPhoto")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.petPhoto)
        self.descName_L = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(20)
        self.descName_L.setFont(font)
        self.descName_L.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.descName_L.setObjectName("descName_L")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.descName_L)
        self.petSpec = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.petSpec.setFont(font)
        self.petSpec.setObjectName("petSpec")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.petSpec)
        self.petMorph = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.petMorph.setFont(font)
        self.petMorph.setObjectName("petMorph")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.petMorph)
        self.petsAgeBirthday = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.petsAgeBirthday.setFont(font)
        self.petsAgeBirthday.setObjectName("petsAgeBirthday")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.petsAgeBirthday)
        self.petsGen = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.petsGen.setFont(font)
        self.petsGen.setObjectName("petsGen")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.petsGen)
        self.petsWeight = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.petsWeight.setFont(font)
        self.petsWeight.setObjectName("petsWeight")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.petsWeight)
        self.petNeutered = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.petNeutered.setFont(font)
        self.petNeutered.setObjectName("petNeutered")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.petNeutered)
        self.petsVacs = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.petsVacs.setFont(font)
        self.petsVacs.setObjectName("petsVacs")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.petsVacs)
        self.petsMicrochip = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.petsMicrochip.setFont(font)
        self.petsMicrochip.setObjectName("petsMicrochip")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.petsMicrochip)
        self.petsLivein = QtWidgets.QLabel(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(14)
        self.petsLivein.setFont(font)
        self.petsLivein.setObjectName("petsLivein")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.FieldRole, self.petsLivein)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)
        self.eventActions = QtWidgets.QHBoxLayout()
        self.eventActions.setContentsMargins(-1, 0, -1, -1)
        self.eventActions.setObjectName("eventActions")
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.eventActions.addItem(spacerItem1)
        self.pushToRedact = QtWidgets.QPushButton(parent=self.containerPet)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(12)
        self.pushToRedact.setFont(font)
        self.pushToRedact.setObjectName("pushToRedact")
        self.eventActions.addWidget(self.pushToRedact)
        self.eventActions.setStretch(0, 4)
        self.eventActions.setStretch(1, 3)
        self.formLayout.setLayout(15, QtWidgets.QFormLayout.ItemRole.FieldRole, self.eventActions)
        self.horizontalLayout.addWidget(self.containerPet)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        _translate = QtCore.QCoreApplication.translate
        self.descName_L.setText(_translate("MainWindow", "Имя питомца"))
        self.petSpec.setText(_translate("MainWindow", "Вид"))
        self.petMorph.setText(_translate("MainWindow", "Порода"))
        self.petsAgeBirthday.setText(_translate("MainWindow", "Возраст и день рождения"))
        self.petsGen.setText(_translate("MainWindow", "Пол"))
        self.petsWeight.setText(_translate("MainWindow", "Вес"))
        self.petNeutered.setText(_translate("MainWindow", "Кастрирован:"))
        self.petsVacs.setText(_translate("MainWindow", "Прививки: (название прививки и дата прививки)"))
        self.petsMicrochip.setText(_translate("MainWindow", "Микрочип:"))
        self.petsLivein.setText(_translate("MainWindow", "Живёт в:"))
        self.pushToRedact.setText(_translate("MainWindow", "Редактировать"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainPage.setText(_translate("MainWindow", "Главная"))
        self.petsPage.setText(_translate("MainWindow", "Питомцы"))
        self.schedPage.setText(_translate("MainWindow", "Расписание"))
        self.cagesPage.setText(_translate("MainWindow", "Клетки"))
        self.pushToCreateM.setText(_translate("MainWindow", "Добавить"))
        self.pushToRedactM.setText(_translate("MainWindow", "Редактировать"))
        self.pushToSearch.setText(_translate("MainWindow", "Найти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.exec()
    sys.exit()